version: '3.4'

services:
  airlineapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  carserviceapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

